name: Run unit test, e2e test and eslint when PR created

on:
  pull_request:

jobs:
  eslint-and-test:
    name: run eslint, tsc, unit test and e2e test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - name: Install Dependencies
        run: yarn install
      - name: setup playwright
        run: npx playwright install --with-deps
      - name: run tsc for typecheck
        run: yarn tsc
      - name: run eslint
        run: yarn lint
      - name: Run unit test with vitest
        run: yarn test:ci
      - name: Run e2e test with paywright
        run: yarn test:e2e
